### ISSUE TITLE
Make argument resolving of FormStateInterface optional

### ISSUE THREAD

**Issue by DieterHolvoet** [wieni/wmmodel#18]
## Summary

I think we should remove this line:
```php
is_a($argument->getType(), FormStateInterface::class, true)
```
from `ModelValueResolver`. I'm not against what it does, I just think wmmodel isn't the right place for that. I think a core patch for [this issue](https://www.drupal.org/project/drupal/issues/3006502) in the relevant projects would be better.

**Comment by RobinHoutevelts** [comment]
I agree however let's remove it once that core issue lands?

It's another big change that's easy to miss if we update projects.

**Comment by DieterHolvoet** [comment]
As discussed in Slack: we'll make this optional, behind a flag in config. Existing installations will automatically keep this enabled, while this will be disabled by default for new installations.
